version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/development/Dockerfile.frontend
    ports:
      - '3000:3000'
    environment:
      API_CONTAINER_URL: ${API_CONTAINER_URL}
      API_CLIENT_URL: ${API_CLIENT_URL}
      API_TOKEN: ${API_TOKEN_DEVELOPMENT}
      NEXT_PUBLIC_MEILISEARCH_HOST: ${MEILISEARCH_HOST}
      NEXT_PUBLIC_MEILISEARCH_API_KEY: ${MEILISEARCH_MASTER_KEY}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ru-beget
      S3_ENDPOINT: http://minio:9000
      S3_FORCE_PATH_STYLE: 'true'
      S3_CDN_BASE_URL: http://localhost:9000/${S3_BUCKET}
      NEXT_PUBLIC_ASSET_HOST: ${S3_CDN_BASE_URL}
      WATCHPACK_POLLING: true
    volumes:
      - ../frontend/public:/frontend/public
      - ../frontend/src:/frontend/src
    restart: always
    networks:
      - internal
    depends_on:
      - strapi

  strapi:
    build:
      context: ../strapi
      dockerfile: ../docker/development/Dockerfile.strapi
    ports:
      - '1337:1337'
    environment:
      APP_KEYS: ${APP_KEYS}
      API_CLIENT_URL: ${API_CLIENT_URL}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: database
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_SSL: ${DATABASE_SSL}
      NODE_ENV: ${NODE_ENV}
      MEILISEARCH_HOST: ${MEILISEARCH_HOST}
      MEILISEARCH_MASTER_KEY: ${MEILISEARCH_MASTER_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_TLS: ${REDIS_TLS}
      REDIS_CACHE_DB: ${REDIS_CACHE_DB}
      REDIS_CACHE_PREFIX: ${REDIS_CACHE_PREFIX}
      REDIS_CACHE_TTL: ${REDIS_CACHE_TTL}
      REDIS_CACHE_CONTENT_TYPES: ${REDIS_CACHE_CONTENT_TYPES}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ru-beget
      S3_ENDPOINT: http://minio:9000
      S3_FORCE_PATH_STYLE: 'true'
      S3_CDN_BASE_URL: http://localhost:9000/${S3_BUCKET}
      NEXT_PUBLIC_ASSET_HOST: ${S3_CDN_BASE_URL}
    volumes:
      - ../strapi/config:/strapi/config
      - ../strapi/database:/strapi/database
      - ../strapi/public:/strapi/public
      - ../strapi/src:/strapi/src
    restart: always
    networks:
      - internal
    depends_on:
      - database
      - meilisearch
      - redis
      - minio

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgresql_database:/var/lib/postgresql/data
    restart: always
    networks:
      - internal

  meilisearch:
    image: getmeili/meilisearch:v1.7
    ports:
      - '7700:7700'
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_MASTER_KEY}
    volumes:
      - meilisearch_data:/meili_data
    restart: always
    networks:
      - internal

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - internal

  minio:
    image: minio/minio
    command: server /data --console-address :9001
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
    volumes:
      - minio-data:/data
    restart: always
    networks:
      - internal

volumes:
  postgresql_database:
  meilisearch_data:
  redis_data:
  minio-data:

networks:
  internal:
